name: 'notify-deploys'
description: 'Notify #aselo-deploys channel with a custom message'
inputs:
  aws-access-key-id:
    description: 'AWS credentials for Aselo user'
    required: true
  aws-secret-access-key:
    description: 'AWS credentials for Aselo user'
    required: true
  aws-region:
    description: 'AWS region where parameters are hosted'
    required: true
  slack-message:
    description: 'The message to send'
    required: true
runs:
  using: "composite"
  steps:
    # Setup credentials to access AWS for parameters
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    # Set env vars to send slack message
    - name: Set GITHUB_ACTIONS_SLACK_BOT_TOKEN
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "GITHUB_ACTIONS_SLACK_BOT_TOKEN"
        env_variable_name: "GITHUB_ACTIONS_SLACK_BOT_TOKEN"
    - name: Set ASELO_DEPLOYS_CHANNEL_ID
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "ASELO_DEPLOYS_CHANNEL_ID"
        env_variable_name: "ASELO_DEPLOYS_CHANNEL_ID"
    # Send Slack notifying success
    - name: Slack Aselo channel
      id: slack
      uses: slackapi/slack-github-action@v1.14.0
      with:
        channel-id: ${{ env.ASELO_DEPLOYS_CHANNEL_ID }}
        slack-message: ${{ inputs.slack-message }}
      env:
        SLACK_BOT_TOKEN: ${{ env.GITHUB_ACTIONS_SLACK_BOT_TOKEN }}