version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/scripts/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    allow:
      - dependency-name: "*"
        dependency-type: "production"
        
  - package-ecosystem: "npm"
    directory: "/plugin-hrm-form/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    allow:
      - dependency-name: "*"
        dependency-type: "production"
        
  - package-ecosystem: "npm"
    directory: "/hrm-form-definitions/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    allow:
      - dependency-name: "*"
        dependency-type: "production"
