const context = {
  ACCOUNT_SID: 'AC_FAKE_UI_TEST_ACCOUNT',
  WORKSPACE_SID: 'WS_FAKE_WORKSPACE',
  LOGGED_IN_WORKER_SID: 'WK_LOGGED_IN_WORKER',
  FLEX_SSO_TOKEN: 'STUB_FLEX_SSO_TOKEN',
};

export default context;
