name: 'install-flex-plugin'
description: 'install flex plugin'
runs:
  using: "composite"
  steps:
    - name: Install the Twilio CLI and plugins
      run: npm install -g twilio-cli  && twilio plugins:install @twilio-labs/plugin-flex@6.0.3
      shell: bash
    - name: Install hrm-form-definitions Packages
      run: npm ci
      working-directory: ./hrm-form-definitions
      shell: bash
    - name: Install plugin-hrm-form Packages
      run: npm ci
      working-directory: ./plugin-hrm-form
      shell: bash
