# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

name: 'run-e2e-tests'
description: 'run e2e tests'
inputs:
  aws-access-key-id:
    description: 'AWS credentials for Aselo user'
    required: false
  aws-secret-access-key:
    description: 'AWS credentials for Aselo user'
    required: false
  path:
    description: 'path to the plugin repo root'
    required: false
    default: '.'
  helpline-shortcode:
    description: 'helpline short code'
    required: false
    default: 'e2e'
  environment:
    description: 'environment'
    required: false
    default: 'development'
  run-ui-tests:
    description: 'run ui tests'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      if: ${{ inputs.run-ui-tests == 'false' }}
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1

    - name: Install e2e-tests dependencies
      run: npm ci
      working-directory: ${{ inputs.path }}/e2e-tests
      shell: bash

    - name: Setup dependencies for playwright/browsers
      uses: microsoft/playwright-github-action@v1

    - name: Install Playwright Browsers
      run: npm run postinstall
      working-directory: ${{ inputs.path }}/e2e-tests
      shell: bash

    - name: Run Playwright tests
      if: ${{ inputs.run-ui-tests == 'false' }}
      run: LOAD_SSM_CONFIG=true HL=${{inputs.helpline-shortcode}} HL_ENV=${{inputs.environment}} npm run test
      working-directory: ${{ inputs.path }}/e2e-tests
      shell: bash

    - name: Run UI tests
      if: ${{ inputs.run-ui-tests == 'true' }}
      run: npm run test:ui
      working-directory: ${{ inputs.path }}/e2e-tests
      shell: bash

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: test-artifacts
        path: ${{ inputs.path }}/e2e-tests/test-results
