export enum ChatStatementOrigin {
  BOT,
  CALLER,
  COUNSELOR,
  COUNSELOR_AUTO, // A message originating from the 'counselor', but generated by the flex client as a result of an action other than typing in the message manually, e.g. the welcome message when a task is picked up, canned responses etc
}

export type ChatStatement = { text: string; origin: ChatStatementOrigin };

export function botStatement(text: string): ChatStatement {
  return {
    text,
    origin: ChatStatementOrigin.BOT,
  };
}

export function callerStatement(text: string): ChatStatement {
  return {
    text,
    origin: ChatStatementOrigin.CALLER,
  };
}

export function counselorStatement(text: string): ChatStatement {
  return {
    text,
    origin: ChatStatementOrigin.COUNSELOR,
  };
}

export function counselorAutoStatement(text: string): ChatStatement {
  return {
    text,
    origin: ChatStatementOrigin.COUNSELOR_AUTO,
  };
}
