/**
 * Copyright (C) 2021-2023 Technology Matters
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see https://www.gnu.org/licenses/.
 */

export enum ChatStatementOrigin {
  BOT,
  CALLER,
  COUNSELOR,
  COUNSELOR_AUTO, // A message originating from the 'counselor', but generated by the flex client as a result of an action other than typing in the message manually, e.g. the welcome message when a task is picked up, canned responses etc
}

export type ChatStatement = { text: string; origin: ChatStatementOrigin };

export function botStatement(text: string): ChatStatement {
  return {
    text,
    origin: ChatStatementOrigin.BOT,
  };
}

export function callerStatement(text: string): ChatStatement {
  return {
    text,
    origin: ChatStatementOrigin.CALLER,
  };
}

export function counselorStatement(text: string): ChatStatement {
  return {
    text,
    origin: ChatStatementOrigin.COUNSELOR,
  };
}

export function counselorAutoStatement(text: string): ChatStatement {
  return {
    text,
    origin: ChatStatementOrigin.COUNSELOR_AUTO,
  };
}
