import { config } from 'dotenv';
config();

const environmentVariables = {
  PLAYWRIGHT_USER_USERNAME: process.env.PLAYWRIGHT_USER_USERNAME,
  PLAYWRIGHT_USER_PASSWORD: process.env.PLAYWRIGHT_USER_PASSWORD,
  PLAYWRIGHT_BASEURL: process.env.PLAYWRIGHT_BASEURL,
  PLAYWRIGHT_BROWSER_TELEMETRY_LEVEL: process.env.PLAYWRIGHT_BROWSER_TELEMETRY_LEVEL,
  PLAYWRIGHT_BROWSER_TELEMETRY_LOG_RESPONSE_BODY:
    process.env.PLAYWRIGHT_BROWSER_TELEMETRY_LOG_RESPONSE_BODY,
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  DEBUG: process.env.DEBUG,
};

export default environmentVariables;
