export const HANDLE_BLUR = 'HANDLE_BLUR';
export const HANDLE_FOCUS = 'HANDLE_FOCUS';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const HANDLE_SELECT_SEARCH_RESULT = 'HANDLE_SELECT_SEARCH_RESULT';
export const INITIALIZE_CONTACT_STATE = 'INITIALIZE_CONTACT_STATE';
export const SAVE_CONTACT_STATE = 'SAVE_CONTACT_STATE';
export const REMOVE_CONTACT_STATE = 'REMOVE_CONTACT_STATE';
