export const HANDLE_BLUR = 'HANDLE_BLUR';
export const HANDLE_VALIDATE_FORM = 'HANDLE_VALIDATE_FORM';
export const HANDLE_FOCUS = 'HANDLE_FOCUS';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const SAVE_END_MILLIS = 'SAVE_END_MILLIS';
export const CHANGE_TAB = 'CHANGE_TAB';
export const RESTORE_ENTIRE_FORM = 'RESTORE_ENTIRE_FORM';

// Autopilot Prepopulate Form
export const PREPOPULATE_FORM_CHILD = 'PREPOPULATE_FORM_CHILD';
export const PREPOPULATE_FORM_CALLER = 'PREPOPULATE_FORM_CALLER';

// Search Contact
export const HANDLE_SELECT_SEARCH_RESULT = 'HANDLE_SELECT_SEARCH_RESULT';
export const HANDLE_SEARCH_FORM_CHANGE = 'HANDLE_SEARCH_FORM_CHANGE';
export const CHANGE_SEARCH_PAGE = 'CHANGE_SEARCH_PAGE';
export const VIEW_CONTACT_DETAILS = 'VIEW_CONTACT_DETAILS';
export const SEARCH_CONTACTS_REQUEST = 'SEARCH_CONTACTS_REQUEST';
export const SEARCH_CONTACTS_SUCCESS = 'SEARCH_CONTACTS_SUCCESS';
export const SEARCH_CONTACTS_FAILURE = 'SEARCH_CONTACTS_FAILURE';
export const HANDLE_EXPAND_DETAILS_SECTION = 'HANDLE_EXPAND_DETAILS_SECTION';

// Categories
export const SET_CATEGORIES_GRID_VIEW = 'SET_CATEGORIES_GRID_VIEW';
export const HANDLE_EXPAND_CATEGORY = 'HANDLE_EXPAND_CATEGORY';
