# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

name: 'Generate production release'
description: 'Given a QA pre release tag, will generate production ready release for the tagged version'
inputs:
  tag-name:
    description: Tag name - The name for the tag that will be given to this release.
    required: true
  title:
    description: Release title - The title that will be given to this release.
    required: true
outputs:
  generated-release-tag:
    description: "The generated release tag"
    value: ${{ inputs.tag-name }}

runs:
  using: "composite"
  steps:
    - name: Validate ref type
      shell: bash
      env:
        REF_TYPE: ${{ github.ref_type }}
      run: |
        if [ $REF_TYPE != 'tag' ] 
        then  
          echo "::error::ERROR - The ref provided is not a tag."
          exit 1
        fi

    # Create a release
    - name: Create a release
      uses: ncipollo/release-action@v1.12.0
      with:
        commit: ${{ github.sha }}
        tag: ${{ inputs.tag-name }}
        name: ${{ inputs.title }}
        body: "TO-DO"
        prerelease: false
      id: create_release
