name: 'Generate production release'
description: 'Given a QA pre release tag, will generate production ready release for the tagged version'
inputs:
  title:
    description: Release title - The title that will be given to this pre-release.
    required: true
  ref_name:
    description: The qa tag name from which to cut ths release.
    required: true
  repository:
    required: true
    description: The github repo to compare tags against. Tipically github.repository.
  repo_token: 
    description: A GitHub token to access the repo. Tipically secrets.GITHUB_TOKEN.
    required: true
outputs:
  generated-release-tag:
    description: "The generated release tag"
    value: ${{ steps.create_release.outputs.automatic_releases_tag }}

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    # Get release tag
    - name: Get release tag
      run: npm run get-release-tag
      env:
        REF: ${{ inputs.ref_name }}
      working-directory: ${{ github.action_path }}
      shell: bash
      id: get_release_tag

    - run: echo ${{ steps.get_release_tag.outputs.generated-tag }}
      shell: bash

    # Create a release
    - name: Create a release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: ${{ inputs.repo_token }}
        automatic_release_tag: ${{ steps.generate_next_tag.outputs.generated-tag }}
        prerelease: false
        title: ${{ inputs.title }}
        # files: |
        #   LICENSE.txt
        #   *.jar
      id: create_release
