/**
 * Copyright (C) 2021-2023 Technology Matters
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see https://www.gnu.org/licenses/.
 */

import { Translations, Configuration, MapHelplineLanguage, ContactType } from '../types';
import type { PreEngagementFormDefinition } from '../src/pre-engagement-form';

const accountSid = 'ACeb335f4685aa874fddf00cdd7c2946bd';
const flexFlowSid = 'FO45c6ac308207b8b17bd990eadf5246fe';
const defaultLanguage = 'en-CA';
const captureIp = false;
const checkOpenHours = false;
const contactType: ContactType = 'ip';
const enableRecaptcha = true;

const translations: Translations = {
  'en-CA': {
    MessageInputDisabledReasonHold: 'Thank you! Please hold for a counsellor.',
    EntryPointTagLine: 'Tap to Chat',
    PreEngagementDescription: "Let's get started",
    Today: 'Today',
    InputPlaceHolder: 'Type Message',
    WelcomeMessage: 'Welcome to Kids Help Phone. ',
    Yesterday: 'Yesterday',
    TypingIndicator: 'Counsellor is typing',
    MessageCanvasTrayButton: 'Start New Chat',
    MessageCanvasTrayContent: '',
    AutoFirstMessage: 'Incoming webchat contact from',
    StartChat: 'Start Chat!',

    PreEngagementConfigDescription:
      'Welcome to Kids Help Phone. To help us serve you better, please answer the following questions. If this is an emergency, please call 911.',
    LabelNickname: 'Nickname (please do not share your real name)',
    NameNickname: 'nickname',
    Guest: 'Guest',
    HowOldAreYou: 'How old are you?',
    Age: 'age',
    FiveOrYounger: '5 or younger',
    PreferNotToAnswer: 'Prefer not to answer',
    DoYouConsiderYourselfToBe: 'Do you consider yourself to be:',
    Gender: 'gender',
    Agender: 'Agender',
    CisMaleMan: 'Cis Male/Man',
    CisFemaleWoman: 'Cis Female/Woman',
    NonBinaryGenderqueerGenderFluid: 'Non-Binary/Genderqueer/Gender fluid',
    TwoSpirit: 'Two-Spirit',
    TransFemaleWoman: 'Trans Female/Woman',
    TransMaleMan: 'Trans Male/Man',
    SexualOrientation: 'sexualOrientation',
    Asexual: 'Asexual',
    BisexualOrPansexual: 'Bisexual or Pansexual',
    GayOrLesbian: 'Gay or Lesbian',
    Queer: 'Queer',
    HeterosexualOrStraight: 'Heterosexual or Straight',
    QuestioningOrUnsure: 'Questioning or Unsure',
    Other: 'Other',
    LabelNewcomer:
      'Are you a newcomer (i.e., Arrived in Canada within 5 years or less), recent immigrant, and/or refugee?',
    NameNewcomer: 'Newcomer',
    Yes: 'Yes',
    No: 'No',
    LabelProvince: 'What province or territory do you live in?',
    NameProvince: 'province',
    Alberta: 'Alberta',
    BritishColumbia: 'British Columbia',
    Inuvialuit: 'Inuvialuit',
    Manitoba: 'Manitoba',
    NewBrunswick: 'New Brunswick',
    NewfoundlandAndLabrador: 'Newfoundland and Labrador',
    NorthwestTerritories: 'Northwest Territories',
    NovaScotia: 'Nova Scotia',
    Nunavat: 'Nunavat',
    Nunavik: 'Nunavik',
    Nunatsiavut: 'Nunatsiavut',
    Ontario: 'Ontario',
    PrinceEdwardIsland: 'Prince Edward Island',
    Quebec: 'Québec',
    Saskatchewan: 'Saskatchewan',
    Yukon: 'Yukon',
    ContactingOutsideCanada: 'Contacting us from outside of Canada',
    TellMoreAboutLive: 'Tell us more about where you live…',
    Region: 'region',
    RuralArea: 'Rural area (less than 1,000 people)',
    SmallCityTown: 'Small city/town (approximately 1,000 to 29,999 people)',
    MediumCity: 'Medium city (approximately 30,000 to 99,999 people)',
    LargeCityUrbanCentre: 'Large city/urban centre (approximately 100,000 people or more)',
    FirstNationsreserve: 'First Nations reserve',
    LabelScale: 'On a scale of 1 to 7, how upset are you right now?',
    Upset: 'upset',
    NotVery: '1 - Not Very',
    Very: '7 - Very',
    Ethnicity: 'ethnicity',
    BlackEthnicity: 'Black (e.g., African, Afro-Caribbean, African Canadian descent)',
    EastAsian: 'East Asian (e.g., East Asian descent; Korean, Chinese, Japanese, etc.)',
    IndigenousToNorthAmerica: 'Indigenous (To North America)',
    FirstNationsToNorthAmerica: 'First Nations [sub-category of Indigenous (To North America)]',
    MetisToNorthAmerica: 'Métis [sub-category of Indigenous (To North America)]',
    Inuit: 'Inuit [sub-category of Indigenous (To North America)]',
    IndigenousNonSpecified: 'Indigenous (non-specified) [sub-category of Indigenous (To North America)]',
    IndigenousNotToNorthAmerica: 'Indigenous (Not to North America)',
    LatinAmerican: 'Latin American (e.g., Latin American, Hispanic descent)',
    MiddleEastern:
      'Middle Eastern (e.g., Arab, Persian, West Asian descent; Egyptian, Iranian, Lebanese, Turkish, etc.)',
    SoutheastAsian:
      'Southeast Asian (e.g., Southeast Asian descent; Cambodian, Filipino, Indonesian, Laotian, Vietnamese, etc.)',
    SouthAsian: 'South Asian (e.g., South Asian descent; East Indian, Afghan, Pakistani, Sri Lankan, etc.)',
    WhiteEuropeanDescent: 'White (e.g., European descent)',
    LabelSchool: 'We would like to learn more about you and if you are currently a student. Do you attend...?',
    School: 'school',
    ElementarySchool: 'Elementary School',
    MiddleschoolJuniorHigh: 'Middle school/Junior High',
    HighSchool: 'High School',
    AlternativeEducationSchoolProgram: 'Alternative Education School/Program',
    College: 'College',
    University: 'University',
    HomeSchool: 'Home School',
    NotAStudent: 'Not a student',
    LabelLivingSituation: 'Which of these best describes your current living situation?:',
    NameLivingSituation: 'livingSituation',
    LivingWithFamilyMembersGuardians: 'Living with family members/guardians',
    MemberMilitaryFamily: 'Member of a military family',
    LivingIndependentlyWithPeers: 'Living independently/with peers',
    LivingSchoolResidence: 'Living in a School residence',
    InHospital: 'In hospital',
    TreatmentCentre: 'Treatment centre',
    RecoveryHome: 'Recovery home',
    AssistedLivingCentre: 'Assisted living centre',
    Homeless: 'Homeless (living in a shelter, on the streets or staying with people temporarily)',
    InCare: 'In care',
    LabelSupportType: 'There are many ways our counsellors can support you. Which of these options apply best to the chat you want to have?',
    LabelSuicidalThoughts: 'Sometimes when people reach out to us, they might also be having thoughts of suicide. We really care about your safety and well-being at Kids Help Phone, we are wondering if you are having any of these thoughts. (A counsellor will also ask this question again in the session to confirm)',
    IWantToTalkAboutMyFeelings: 'I want to talk about my feelings',
    ImLookingForTipsAndStrategies: 'I\'m looking for tips and strategies',
    IWantSupportToSolveAConflict: 'I want support to solve a conflict/problem',
    INeedHelpToBeSafer: 'I need help to be safer',
    IWantToKnowHowToHelpSomeoneElse: 'I want to know how to help someone else',
    INeedHelpFindingAResource: 'I need help finding a resource/information',
  },
  'fr-CA': {
    WelcomeMessage: "Bienvenue à Jeunesse, J'écoute",
    MessageCanvasTrayContent: '',
    MessageInputDisabledReasonHold:
      "Je vous remercie beaucoup pour l'info. Nous allons le transférer maintenant. Veuillez attendre un agent.",
    AutoFirstMessage: 'Nouveau contact de web',
    TypingIndicator: '{0} est écrit ... ',
    StartChat: 'Démarrer la chat!',
    MessageCanvasTrayButton: 'Démarrer une nouvelle chat',
    EntryPointTagline: 'Tape ici pour clavarder',
    InvalidPreEngagementMessage:
      "Les formulaires de pré-engagement n'ont pas été établis et sont nécessaires pour démarrer le chat Web. Veuillez les configurer maintenant dans les paramètres.",
    InvalidPreEngagementButton: 'Apprendre encore plus',
    PredefinedChatMessageAuthorName: 'Bot',
    PredefinedChatMessageBody: "Salut! Que peut-on faire pour vous aider aujourd'hui?",
    InputPlaceHolder: 'Écrire un message',
    Read: 'Vu',
    MessageSendingDisabled: "L'envoi de messages a été désactivé",
    Today: "Aujourd'hui",
    Yesterday: 'Hier',
    Save: 'Sauvegarder',
    Reset: 'RÉINITIALISER',
    MessageCharacterCountStatus: '{{currentCharCount}} / {{maxCharCount}}',
    SendMessageTooltip: 'Envoyer un message',
    FieldValidationRequiredField: 'Champs requis',
    PreEngagementDescription: 'Commençons',
    BotGreeting: 'Comment je peux aider?',

    PreEngagementConfigDescription:
      "Bienvenue à Jeunesse, J'écoute. Pour nous aider à mieux vous servir, veuillez répondre aux questions suivantes. S'il s'agit d'une urgence, nous te prions d’appeler le 911.",
    LabelNickname: 'Pseudonyme (Veuillez ne pas partager votre vrai nom)',
    NameNickname: 'nickname',
    Guest: 'Invité',
    HowOldAreYou: 'Quel âge as-tu?',
    Age: 'age',
    FiveOrYounger: '5 ans ou moins',
    PreferNotToAnswer: 'Je préfère ne pas répondre',
    DoYouConsiderYourselfToBe: 'Te considères-tu comme étant:',
    Gender: 'gender',
    Agender: 'Agenre',
    CisMaleMan: 'Garçon/homme cis',
    CisFemaleWoman: 'Fille/femme cis',
    NonBinaryGenderqueerGenderFluid: 'Non-binaire/genre fluide',
    TwoSpirit: 'Bispirituel',
    TransFemaleWoman: 'Fille/femme trans',
    TransMaleMan: 'Garçon/homme trans',
    SexualOrientation: 'sexualOrientation',
    Asexual: 'Asexuel',
    BisexualOrPansexual: 'Bisexuel ou pansexuel',
    GayOrLesbian: 'Gai ou lesbienne',
    Queer: 'Queer',
    HeterosexualOrStraight: 'Hétérosexuel',
    QuestioningOrUnsure: 'En questionnement ou incertain',
    Other: 'Autre',
    LabelNewcomer:
      'Es-tu un nouvel arrivant (c.-à-d. au Canada depuis 5 ans ou moins) un immigrant récent ou un réfugié?',
    NameNewcomer: 'Newcomer',
    Yes: 'Oui',
    No: 'Non',
    Maybe: 'Peut être',
    LabelProvince: 'Dans quelle province ou quel territoire habites-tu?',
    NameProvince: 'province',
    Alberta: 'Alberta',
    BritishColumbia: 'Colombie-Britannique',
    Inuvialuit: 'Inuvialuit',
    Manitoba: 'Manitoba',
    NewBrunswick: 'Nouveau-Brunswick',
    NewfoundlandAndLabrador: 'Terre-Neuve-et-Labrador',
    NorthwestTerritories: 'Territoires du Nord-Ouest',
    NovaScotia: 'Nouvelle-Écosse',
    Nunavat: 'Nunavat',
    Nunavik: 'Nunavik',
    Nunatsiavut: 'Nunatsiavut',
    Ontario: 'Ontario',
    PrinceEdwardIsland: 'Île-du-Prince-Édouard',
    Quebec: 'Québec',
    Saskatchewan: 'Saskatchewan',
    Yukon: 'Yukon',
    ContactingOutsideCanada: 'La personne demeure en dehors du Canada',
    TellMoreAboutLive: 'Dis nous la grandeur de la place où tu habites?',
    Region: 'region',
    RuralArea: 'Région rurale (moins de 1 000 habitants)',
    SmallCityTown: 'Petite ville ou municipalité (environ 1 000 à 29 999 habitants)',
    MediumCity: 'Ville moyenne (environ 30 000 à 99 999 habitants)',
    LargeCityUrbanCentre: 'Grande ville ou centre urbain (environ 100 000 habitants ou plus)',
    FirstNationsreserve: 'Réserve des Premières Nations',
    LabelScale: 'Sur une échelle de 1 à 7, à quel point es-tu bouleversé en ce moment?',
    Upset: 'upset',
    NotVery: '1 - Pas tellement',
    Very: '7 - Extrêmement',
    Ethnicity: 'ethnicity',
    BlackEthnicity: 'Noir (p. ex., Africain, Afro-Antillais, Canadien d’origine africaine)',
    EastAsian: 'Asiatique de l’Est (p. ex., originaire de l’Asie de l’Est, Coréen, Chinois, Japonais)',
    IndigenousToNorthAmerica: 'Indigène (de l’Amérique du Nord)',
    FirstNationsToNorthAmerica: 'Premières Nations',
    MetisToNorthAmerica: 'Métis',
    Inuit: 'Inuit',
    IndigenousNonSpecified: 'Autochtone (non spécifié)',
    IndigenousNotToNorthAmerica: 'Indigène (provenant d’ailleurs que l’Amérique du Nord)',
    LatinAmerican: 'Latino-américain (p. ex., Latino-Américain, d’origine hispanique)',
    MiddleEastern:
      'Provenant du Moyen-Orient (p. ex., d’origine Arabe, Perse ou d’Asie de l’Ouest; Égyptien, Iranien, Libanais, Turque)',
    SoutheastAsian:
      'Asiatique du Sud-Est (p. ex., originaire de l’Asie du Sud-Est, Cambodgien, Philippin, Indonésien, Laotien, Vietnamien)',
    SouthAsian: 'Asiatique du Sud (p. ex., originaire de l’Asie du Sud, Indien d’Asie, Pakistanais, Sri Lankais)',
    WhiteEuropeanDescent: 'Blanc (p. ex., d’origine européenne)',
    LabelSchool:
      'Nous aimerions en apprendre plus sur toi et savoir si tu es actuellement aux études. Es-tu présentement...?',
    School: 'school',
    ElementarySchool: 'À l’école primaire',
    MiddleschoolJuniorHigh: 'Au secondaire (premier cycle)',
    HighSchool: 'Au secondaire',
    AlternativeEducationSchoolProgram: 'Dans une école/un programme de formation alternative',
    College: 'Au collège/cégep',
    University: 'À l’université',
    HomeSchool: 'Scolarisé à la maison',
    NotAStudent: 'Pas aux études',
    LabelLivingSituation:
      'Qu’est-ce qui décrit le mieux ta situation actuelle? (Choisir toutes les réponses qui s’appliquent.):',
    NameLivingSituation: 'livingSituation',
    LivingWithFamilyMembersGuardians: 'Vivant avec les membres de la famille/tuteurs',
    MemberMilitaryFamily: 'Membre d’une famille militaire',
    LivingIndependentlyWithPeers: 'Vivant seul/avec des pairs',
    LivingSchoolResidence: 'Vivant dans une résidence scolaire',
    InHospital: 'Hospitalisé',
    TreatmentCentre: 'centre de désintoxication',
    RecoveryHome: 'Centre de rétablissement',
    AssistedLivingCentre: 'Centre avec services de soutien',
    Homeless: 'Sans-abri (p. ex., vivant dans un refuge, dans la rue, temporairement chez quelqu’un d’autre)',
    InCare: 'Dans les soins',
    LabelSupportType: 'Notre intervenant peut te venir en aide de différentes façons selon ton besoin. Laquelle de ces optionss’applique le mieux au clavardage que tu aimerais avoir?',
    LabelSuicidalThoughts: 'Parfois, lorsque les gens nous contactent, ils peuvent aussi avoir des pensées suicidaires. Chez Jeunesse, J’écoute, nous nous soucions vraiment de ta sécurité et de ton bien-être. Nous aurions besoin de savoir-as-tu des pensées suicidaires? (Un conseiller reposera également cette question en séance pour confirmer)',
    IWantToTalkAboutMyFeelings: 'Je veux parler de mes sentiments',
    ImLookingForTipsAndStrategies: 'Je recherche des conseils et des stratégies',
    IWantSupportToSolveAConflict: 'Je veux du soutien pour résoudre un conflit/problème',
    INeedHelpToBeSafer: 'J’ai besoin d’aide pour être plus en sécurité',
    IWantToKnowHowToHelpSomeoneElse: 'Je veux savoir comment aider quelqu’un d’autre',
    INeedHelpFindingAResource: 'J’ai besoin d’aide pour trouver une ressource/des informations',
  },
};

const preEngagementConfig: PreEngagementFormDefinition = {
  description: 'PreEngagementConfigDescription',
  submitLabel: 'StartChat',
  fields: [
    {
      type: 'input-text',
      name: 'nickname',
      label: 'LabelNickname',
      placeholder: 'Guest',
      required: true,
    },
    {
      type: 'select',
      name: 'age',
      label: 'HowOldAreYou',
      defaultValue: 'Unknown',
      required: true,
      options: [
        { value: '5 or younger', label: 'FiveOrYounger' },
        { value: '06', label: '6' },
        { value: '07', label: '7' },
        { value: '08', label: '8' },
        { value: '09', label: '9' },
        { value: '10', label: '10' },
        { value: '11', label: '11' },
        { value: '12', label: '12' },
        { value: '13', label: '13' },
        { value: '14', label: '14' },
        { value: '15', label: '15' },
        { value: '16', label: '16' },
        { value: '17', label: '17' },
        { value: '18', label: '18' },
        { value: '19', label: '19' },
        { value: '20', label: '20' },
        { value: '21', label: '21' },
        { value: '22', label: '22' },
        { value: '23', label: '23' },
        { value: '24', label: '24' },
        { value: '25', label: '25' },
        { value: '26', label: '26' },
        { value: '27', label: '27' },
        { value: '28', label: '28' },
        { value: '29', label: '29' },
        { value: '>30', label: '>30' },
        { value: 'Unknown', label: 'PreferNotToAnswer' },
      ],
    },
    {
      type: 'select',
      name: 'gender',
      label: 'DoYouConsiderYourselfToBe',
      defaultValue: 'Unknown',
      required: true,
      options: [
        { value: 'Agender', label: 'Agender' },
        { value: 'Cis Male/Man', label: 'CisMaleMan' },
        { value: 'Cis Female/Woman', label: 'CisFemaleWoman' },
        { value: 'Non-Binary/Genderqueer/Gender fluid', label: 'NonBinaryGenderqueerGenderFluid' },
        { value: 'Two-Spirit', label: 'TwoSpirit' },
        { value: 'Trans Female/Woman', label: 'TransFemaleWoman' },
        { value: 'Trans Male/Man', label: 'TransMaleMan' },
        { value: 'Other', label: 'Other' },
        { value: 'Unknown', label: 'PreferNotToAnswer' },
      ],
    },
    {
      type: 'select',
      name: 'sexualOrientation',
      label: 'DoYouConsiderYourselfToBe',
      defaultValue: 'Unknown',
      required: true,
      options: [
        { value: 'Asexual', label: 'Asexual' },
        { value: 'Bisexual or Pansexual', label: 'BisexualOrPansexual' },
        { value: 'Gay or Lesbian', label: 'GayOrLesbian' },
        { value: 'Queer', label: 'Queer' },
        { value: 'Heterosexual or Straight', label: 'HeterosexualOrStraight' },
        { value: 'Questioning or Unsure', label: 'QuestioningOrUnsure' },
        { value: 'Other', label: 'Other' },
        { value: 'Unknown', label: 'PreferNotToAnswer' },
      ],
    },
    {
      type: 'select',
      name: 'Newcomer',
      label: 'LabelNewcomer',
      defaultValue: 'Unknown',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
        { value: 'Unknown', label: 'PreferNotToAnswer' },
      ],
    },
    {
      type: 'select',
      name: 'province',
      label: 'LabelProvince',
      defaultValue: 'Unknown',
      required: true,
      options: [
        { value: 'Alberta', label: 'Alberta' },
        { value: 'British Columbia', label: 'BritishColumbia' },
        { value: 'Inuvialuit', label: 'Inuvialuit' },
        { value: 'Manitoba', label: 'Manitoba' },
        { value: 'New Brunswick', label: 'NewBrunswick' },
        { value: 'Newfoundland and Labrador', label: 'NewfoundlandAndLabrador' },
        { value: 'Northwest Territories', label: 'NorthwestTerritories' },
        { value: 'Nova Scotia', label: 'NovaScotia' },
        { value: 'Nunavat', label: 'Nunavat' },
        { value: 'Nunavik', label: 'Nunavik' },
        { value: 'Nunatsiavut', label: 'Nunatsiavut' },
        { value: 'Ontario', label: 'Ontario' },
        { value: 'Prince Edward Island', label: 'PrinceEdwardIsland' },
        { value: 'Québec', label: 'Quebec' },
        { value: 'Saskatchewan', label: 'Saskatchewan' },
        { value: 'Yukon', label: 'Yukon' },
        { value: 'Contacting us from outside of Canada', label: 'ContactingOutsideCanada' },
        { value: 'Unknown', label: 'PreferNotToAnswer' },
      ],
    },
    {
      type: 'select',
      name: 'region',
      label: 'TellMoreAboutLive',
      defaultValue: 'Unknown',
      required: true,
      options: [
        { value: 'Rural area', label: 'RuralArea' },
        { value: 'Small city/town', label: 'SmallCityTown' },
        { value: 'Medium city', label: 'MediumCity' },
        { value: 'Large city/urban centre', label: 'LargeCityUrbanCentre' },
        { value: 'First Nations reserve', label: 'FirstNationsreserve' },
        { value: 'Other', label: 'Other' },
        { value: 'Unknown', label: 'PreferNotToAnswer' },
      ],
    },
    {
      type: 'select',
      name: 'upset',
      label: 'LabelScale',
      defaultValue: '1',
      required: true,
      options: [
        { value: '1', label: 'NotVery' },
        { value: '2', label: '2' },
        { value: '3', label: '3' },
        { value: '4', label: '4' },
        { value: '5', label: '5' },
        { value: '6', label: '6' },
        { value: '7', label: 'Very' },
      ],
    },
    {
      type: 'select',
      name: 'ethnicity',
      label: 'DoYouConsiderYourselfToBe',
      defaultValue: 'Unknown',
      required: false,
      options: [
        { value: '', label: '' },
        { value: 'Black', label: 'BlackEthnicity' },
        { value: 'East Asian', label: 'EastAsian' },
        { value: 'Indigenous', label: 'IndigenousToNorthAmerica' },
        { value: 'First Nations', label: 'FirstNationsToNorthAmerica' },
        { value: 'Métis', label: 'MetisToNorthAmerica' },
        { value: 'Inuit', label: 'Inuit' },
        { value: 'Indigenous (non-specified)', label: 'IndigenousNonSpecified' },
        { value: 'Indigenous (Not to North America)', label: 'IndigenousNotToNorthAmerica' },
        { value: 'Latin American', label: 'LatinAmerican' },
        { value: 'Middle Eastern', label: 'MiddleEastern' },
        { value: 'Southeast Asian', label: 'SoutheastAsian' },
        { value: 'South Asian', label: 'SouthAsian' },
        { value: 'White', label: 'WhiteEuropeanDescent' },
        { value: 'Other', label: 'Other' },
        { value: 'Unknown', label: 'PreferNotToAnswer' },
      ],
    },
    {
      type: 'select',
      name: 'school',
      label: 'LabelSchool',
      defaultValue: 'Unknown',
      required: false,
      options: [
        { value: '', label: '' },
        { value: 'Elementary School', label: 'ElementarySchool' },
        { value: 'Middle school/Junior High', label: 'MiddleschoolJuniorHigh' },
        { value: 'High School', label: 'HighSchool' },
        { value: 'Alternative Education School/Program', label: 'AlternativeEducationSchoolProgram' },
        { value: 'College', label: 'College' },
        { value: 'University', label: 'University' },
        { value: 'Home School', label: 'HomeSchool' },
        { value: 'Other', label: 'Other' },
        { value: 'Not a student', label: 'NotAStudent' },
        { value: 'Unknown', label: 'PreferNotToAnswer' },
      ],
    },
    {
      type: 'select',
      name: 'livingSituation',
      label: 'LabelLivingSituation',
      defaultValue: 'Unknown',
      required: false,
      options: [
        { value: '', label: '' },
        { value: 'Living with family members/guardians', label: 'LivingWithFamilyMembersGuardians' },
        { value: 'Member of a military family', label: 'MemberMilitaryFamily' },
        { value: 'Living independently/with peers', label: 'LivingIndependentlyWithPeers' },
        { value: 'Living in a School residence', label: 'LivingSchoolResidence' },
        { value: 'In hospital', label: 'InHospital' },
        { value: 'Treatment centre', label: 'TreatmentCentre' },
        { value: 'Recovery home', label: 'RecoveryHome' },
        { value: 'Assisted living centre', label: 'AssistedLivingCentre' },
        { value: 'Homeless', label: 'Homeless' },
        { value: 'In care', label: 'InCare' },
        { value: 'Other', label: 'Other' },
        { value: 'Unknown', label: 'PreferNotToAnswer' },
      ],
    },
    {
      type: 'select',
      name: 'supportType',
      label: 'LabelSupportType',
      defaultValue: 'Unknown',
      required: false,
      options: [
        { value: '', label: '' },
        { value: 'I want to talk about my feelings', label: 'IWantToTalkAboutMyFeelings' },
        { value: 'I\'m looking for tips and strategies', label: 'ImLookingForTipsAndStrategies' },
        { value: 'I want support to solve a conflict/problem', label: 'IWantSupportToSolveAConflict' },
        { value: 'I need help to be safer', label: 'INeedHelpToBeSafer' },
        { value: 'I want to know how to help someone else', label: 'IWantToKnowHowToHelpSomeoneElse' },
        { value: 'I need help finding a resource/information', label: 'INeedHelpFindingAResource' },
        { value: 'Unknown', label: 'PreferNotToAnswer' },
      ],
    },
    {
      type: 'select',
      name: 'suicidalThoughts',
      label: 'LabelSuicidalThoughts',
      defaultValue: 'Unknown',
      required: false,
      options: [
        { value: 'Unknown', label: '' },
        { value: 'Yes', label: 'Yes' },
        { value: 'No', label: 'No' },
        { value: 'Maybe', label: 'Maybe' },
      ],
    },
  ],
};

const closedHours: PreEngagementFormDefinition = {
  description:
    "We're sorry, but Live Chat is currently closed. :( \nTo reach a Kids Help Phone counsellor, call us anytime at 1-800-668-6868. \nBe well, \nThe Kids Help Phone Team",
  fields: [],
};

const holidayHours: PreEngagementFormDefinition = {
  description:
    "We're sorry, but Live Chat is currently closed. :( \nTo reach a Kids Help Phone counsellor, call us anytime at 1-800-668-6868. \nBe well, \nThe Kids Help Phone Team",
  fields: [],
};

const memberDisplayOptions = {
  yourDefaultName: 'You',
  yourFriendlyNameOverride: false,
  theirFriendlyNameOverride: false,
  theirDefaultName: 'Counsellor',
};

const mapHelplineLanguage: MapHelplineLanguage = (helpline) => {
  switch (helpline) {
    default:
      return defaultLanguage;
  }
};

const blockedEmojis = [
  'grinning',
  'slightly_smiling_face',
  'melting_face',
  'wink',
  'heart_eyes',
  'kissing_heart',
  'kissing',
  'relaxed',
  'kissing_closed_eyes',
  'kissing_smiling_eyes',
  'smiling_face_with_tear',
  'stuck_out_tongue',
  'stuck_out_tongue_winking_eye',
  'stuck_out_tongue_closed_eyes',
  'money_mouth_face',
  'face_with_open_eyes_and_hand_over_mouth',
  'face_with_peeking_eye',
  'shushing_face',
  'saluting_face',
  'zipper_mouth_face',
  'face_with_raised_eyebrow',
  'neutral_face',
  'expressionless',
  'no_mouth',
  'dotted_line_face',
  'face_in_clouds',
  'face_with_rolling_eyes',
  'face_exhaling',
  'lying_face',
  'relieved',
  'drooling_face',
  'sleeping',
  'mask',
  'face_with_thermometer',
  'face_with_head_bandage',
  'nauseated_face',
  'face_vomiting',
  'sneezing_face',
  'hot_face',
  'cold_face',
  'woozy_face',
  'face_with_spiral_eyes',
  'face_with_cowboy_hat',
  'disguised_face',
  'face_with_monocle',
  'face_with_diagonal_mouth',
  'slightly_frowning_face',
  'hushed',
  'astonished',
  'flushed',
  'face_holding_back_tears',
  'frowning',
  'disappointed_relieved',
  'sob',
  'persevere',
  'disappointed',
  'sweat',
  'weary',
  'tired_face',
  'yawning_face',
  'triumph',
  'angry',
  'smiling_imp',
  'imp',
  'skull',
  'skull_and_crossbones',
  'hankey',
  'clown_face',
  'japanese_ogre',
  'japanese_goblin',
  'ghost',
  'alien',
  'space_invader',
  'robot_face',
  'raised_back_of_hand',
  'raised_hand_with_fingers_splayed',
  'hand',
  'spock-hand',
  'rightwards_hand',
  'leftwards_hand',
  'palm_down_hand',
  'palm_up_hand',
  'ok_hand',
  'pinched_fingers',
  'pinching_hand',
  'v',
  'hand_with_index_finger_and_thumb_crossed',
  'i_love_you_hand_sign',
  'the_horns',
  'call_me_hand',
  'point_left',
  'point_right',
  'point_up_2',
  'middle_finger',
  'point_down',
  'point_up',
  'index_pointing_at_the_viewer',
  'fist',
  'facepunch',
  'left-facing_fist',
  'right-facing_fist',
  'raised_hands',
  'heart_hands',
  'open_hands',
  'palms_up_together',
  'writing_hand',
  'nail_care',
  'selfie',
  'mechanical_arm',
  'mechanical_leg',
  'leg',
  'foot',
  'ear',
  'ear_with_hearing_aid',
  'nose',
  'brain',
  'anatomical_heart',
  'lungs',
  'tooth',
  'bone',
  'eyes',
  'eye',
  'tongue',
  'lips',
  'biting_lip',
  'baby',
  'child',
  'boy',
  'girl',
  'adult',
  'person_with_blond_hair',
  'man',
  'bearded_person',
  'man_with_beard',
  'woman_with_beard',
  'red_haired_man',
  'curly_haired_man',
  'white_haired_man',
  'bald_man',
  'woman',
  'red_haired_woman',
  'red_haired_person',
  'curly_haired_woman',
  'curly_haired_person',
  'white_haired_woman',
  'white_haired_person',
  'bald_woman',
  'bald_person',
  'blond-haired-woman',
  'blond-haired-man',
  'older_adult',
  'older_man',
  'older_woman',
  'person_frowning',
  'man-frowning',
  'woman-frowning',
  'person_with_pouting_face',
  'man-pouting',
  'woman-pouting',
  'no_good',
  'man-gesturing-no',
  'woman-gesturing-no',
  'ok_woman',
  'man-gesturing-ok',
  'woman-gesturing-ok',
  'information_desk_person',
  'man-tipping-hand',
  'woman-tipping-hand',
  'raising_hand',
  'man-raising-hand',
  'woman-raising-hand',
  'deaf_person',
  'deaf_man',
  'deaf_woman',
  'bow',
  'man-bowing',
  'woman-bowing',
  'face_palm',
  'man-facepalming',
  'woman-facepalming',
  'shrug',
  'man-shrugging',
  'woman-shrugging',
  'health_worker',
  'male-doctor',
  'female-doctor',
  'student',
  'male-student',
  'female-student',
  'teacher',
  'male-teacher',
  'female-teacher',
  'judge',
  'male-judge',
  'female-judge',
  'farmer',
  'male-farmer',
  'female-farmer',
  'cook',
  'male-cook',
  'female-cook',
  'mechanic',
  'male-mechanic',
  'female-mechanic',
  'factory_worker',
  'male-factory-worker',
  'female-factory-worker',
  'office_worker',
  'male-office-worker',
  'female-office-worker',
  'scientist',
  'male-scientist',
  'female-scientist',
  'technologist',
  'male-technologist',
  'female-technologist',
  'singer',
  'male-singer',
  'female-singer',
  'artist',
  'male-artist',
  'female-artist',
  'pilot',
  'male-pilot',
  'female-pilot',
  'astronaut',
  'male-astronaut',
  'female-astronaut',
  'firefighter',
  'male-firefighter',
  'female-firefighter',
  'cop',
  'male-police-officer',
  'female-police-officer',
  'sleuth_or_spy',
  'male-detective',
  'female-detective',
  'guardsman',
  'male-guard',
  'female-guard',
  'ninja',
  'construction_worker',
  'male-construction-worker',
  'female-construction-worker',
  'person_with_crown',
  'prince',
  'princess',
  'man_with_turban',
  'man-wearing-turban',
  'woman-wearing-turban',
  'man_with_gua_pi_mao',
  'person_with_headscarf',
  'person_in_tuxedo',
  'man_in_tuxedo',
  'woman_in_tuxedo',
  'bride_with_veil',
  'man_with_veil',
  'woman_with_veil',
  'pregnant_woman',
  'pregnant_man',
  'pregnant_person',
  'breast-feeding',
  'woman_feeding_baby',
  'man_feeding_baby',
  'person_feeding_baby',
  'angel',
  'santa',
  'mrs_claus',
  'mx_claus',
  'superhero',
  'supervillain',
  'male_supervillain',
  'female_supervillain',
  'mage',
  'male_mage',
  'female_mage',
  'fairy',
  'male_fairy',
  'female_fairy',
  'vampire',
  'male_vampire',
  'female_vampire',
  'merperson',
  'merman',
  'mermaid',
  'elf',
  'male_elf',
  'female_elf',
  'genie',
  'male_genie',
  'female_genie',
  'zombie',
  'male_zombie',
  'female_zombie',
  'troll',
  'massage',
  'man-getting-massage',
  'woman-getting-massage',
  'haircut',
  'man-getting-haircut',
  'woman-getting-haircut',
  'walking',
  'man-walking',
  'woman-walking',
  'standing_person',
  'man_standing',
  'woman_standing',
  'kneeling_person',
  'man_kneeling',
  'woman_kneeling',
  'person_with_probing_cane',
  'man_with_probing_cane',
  'woman_with_probing_cane',
  'person_in_motorized_wheelchair',
  'man_in_motorized_wheelchair',
  'woman_in_motorized_wheelchair',
  'person_in_manual_wheelchair',
  'man_in_manual_wheelchair',
  'woman_in_manual_wheelchair',
  'runner',
  'man-running',
  'woman-running',
  'man_in_business_suit_levitating',
  'dancers',
  'men-with-bunny-ears-partying',
  'women-with-bunny-ears-partying',
  'person_in_steamy_room',
  'man_in_steamy_room',
  'woman_in_steamy_room',
  'person_climbing',
  'man_climbing',
  'woman_climbing',
  'fencer',
  'horse_racing',
  'skier',
  'snowboarder',
  'golfer',
  'man-golfing',
  'woman-golfing',
  'surfer',
  'man-surfing',
  'woman-surfing',
  'rowboat',
  'man-rowing-boat',
  'woman-rowing-boat',
  'swimmer',
  'man-swimming',
  'woman-swimming',
  'person_with_ball',
  'man-bouncing-ball',
  'woman-bouncing-ball',
  'weight_lifter',
  'man-lifting-weights',
  'woman-lifting-weights',
  'bicyclist',
  'man-biking',
  'woman-biking',
  'mountain_bicyclist',
  'man-mountain-biking',
  'woman-mountain-biking',
  'man-cartwheeling',
  'woman-cartwheeling',
  'wrestlers',
  'man-wrestling',
  'woman-wrestling',
  'water_polo',
  'man-playing-water-polo',
  'woman-playing-water-polo',
  'handball',
  'man-playing-handball',
  'woman-playing-handball',
  'juggling',
  'man-juggling',
  'woman-juggling',
  'person_in_lotus_position',
  'bath',
  'sleeping_accommodation',
  'people_holding_hands',
  'two_women_holding_hands',
  'man_and_woman_holding_hands',
  'two_men_holding_hands',
  'couplekiss',
  'woman-kiss-man',
  'man-kiss-man',
  'woman-kiss-woman',
  'couple_with_heart',
  'woman-heart-man',
  'man-heart-man',
  'woman-heart-woman',
  'family',
  'man-woman-boy',
  'man-woman-girl',
  'man-woman-girl-boy',
  'man-woman-boy-boy',
  'man-woman-girl-girl',
  'man-man-boy',
  'man-man-girl',
  'man-man-girl-boy',
  'man-man-boy-boy',
  'man-man-girl-girl',
  'woman-woman-boy',
  'woman-woman-girl',
  'woman-woman-girl-boy',
  'woman-woman-boy-boy',
  'woman-woman-girl-girl',
  'man-boy',
  'man-boy-boy',
  'man-girl',
  'man-girl-boy',
  'man-girl-girl',
  'woman-boy',
  'woman-boy-boy',
  'woman-girl',
  'woman-girl-boy',
  'woman-girl-girl',
  'speaking_head_in_silhouette',
  'bust_in_silhouette',
  'busts_in_silhouette',
  'people_hugging',
  'footprints',
  'smiley_cat',
  'smile_cat',
  'joy_cat',
  'smirk_cat',
  'kissing_cat',
  'scream_cat',
  'crying_cat_face',
  'pouting_cat',
  'see_no_evil',
  'hear_no_evil',
  'speak_no_evil',
  'kiss',
  'love_letter',
  'cupid',
  'gift_heart',
  'sparkling_heart',
  'heartpulse',
  'heartbeat',
  'revolving_hearts',
  'two_hearts',
  'heart_decoration',
  'heavy_heart_exclamation_mark_ornament',
  'heart_on_fire',
  'mending_heart',
  'heart',
  'orange_heart',
  'yellow_heart',
  'green_heart',
  'blue_heart',
  'purple_heart',
  'brown_heart',
  'black_heart',
  'white_heart',
  'anger',
  'boom',
  'dizzy',
  'sweat_drops',
  'dash',
  'hole',
  'bomb',
  'speech_balloon',
  'eye-in-speech-bubble',
  'left_speech_bubble',
  'right_anger_bubble',
  'thought_balloon',
  'zzz',
  'monkey_face',
  'monkey',
  'gorilla',
  'orangutan',
  'dog',
  'dog2',
  'guide_dog',
  'service_dog',
  'poodle',
  'wolf',
  'fox_face',
  'raccoon',
  'cat',
  'cat2',
  'black_cat',
  'lion_face',
  'tiger',
  'tiger2',
  'leopard',
  'horse',
  'racehorse',
  'unicorn_face',
  'zebra_face',
  'deer',
  'bison',
  'cow',
  'ox',
  'water_buffalo',
  'cow2',
  'pig',
  'pig2',
  'boar',
  'pig_nose',
  'ram',
  'sheep',
  'goat',
  'dromedary_camel',
  'camel',
  'llama',
  'giraffe_face',
  'elephant',
  'mammoth',
  'rhinoceros',
  'hippopotamus',
  'mouse',
  'mouse2',
  'rat',
  'hamster',
  'rabbit',
  'rabbit2',
  'chipmunk',
  'beaver',
  'hedgehog',
  'bat',
  'bear',
  'polar_bear',
  'koala',
  'panda_face',
  'sloth',
  'otter',
  'skunk',
  'kangaroo',
  'badger',
  'feet',
  'turkey',
  'chicken',
  'rooster',
  'hatching_chick',
  'baby_chick',
  'hatched_chick',
  'bird',
  'penguin',
  'dove_of_peace',
  'eagle',
  'duck',
  'swan',
  'owl',
  'dodo',
  'feather',
  'flamingo',
  'peacock',
  'parrot',
  'frog',
  'crocodile',
  'turtle',
  'lizard',
  'snake',
  'dragon_face',
  'dragon',
  'sauropod',
  't-rex',
  'whale',
  'whale2',
  'dolphin',
  'seal',
  'fish',
  'tropical_fish',
  'blowfish',
  'shark',
  'octopus',
  'shell',
  'coral',
  'snail',
  'butterfly',
  'bug',
  'ant',
  'bee',
  'beetle',
  'ladybug',
  'cricket',
  'cockroach',
  'spider',
  'spider_web',
  'scorpion',
  'mosquito',
  'fly',
  'worm',
  'microbe',
  'bouquet',
  'cherry_blossom',
  'white_flower',
  'lotus',
  'rosette',
  'rose',
  'wilted_flower',
  'hibiscus',
  'blossom',
  'tulip',
  'seedling',
  'potted_plant',
  'evergreen_tree',
  'deciduous_tree',
  'palm_tree',
  'cactus',
  'ear_of_rice',
  'herb',
  'shamrock',
  'maple_leaf',
  'fallen_leaf',
  'leaves',
  'empty_nest',
  'nest_with_eggs',
  'grapes',
  'melon',
  'watermelon',
  'tangerine',
  'lemon',
  'banana',
  'pineapple',
  'mango',
  'apple',
  'green_apple',
  'pear',
  'peach',
  'cherries',
  'strawberry',
  'blueberries',
  'kiwifruit',
  'tomato',
  'olive',
  'coconut',
  'avocado',
  'eggplant',
  'potato',
  'carrot',
  'corn',
  'hot_pepper',
  'bell_pepper',
  'cucumber',
  'leafy_green',
  'broccoli',
  'garlic',
  'onion',
  'mushroom',
  'peanuts',
  'beans',
  'chestnut',
  'bread',
  'croissant',
  'baguette_bread',
  'flatbread',
  'pretzel',
  'bagel',
  'pancakes',
  'waffle',
  'cheese_wedge',
  'meat_on_bone',
  'poultry_leg',
  'cut_of_meat',
  'bacon',
  'hamburger',
  'fries',
  'pizza',
  'hotdog',
  'sandwich',
  'taco',
  'burrito',
  'tamale',
  'stuffed_flatbread',
  'falafel',
  'egg',
  'fried_egg',
  'shallow_pan_of_food',
  'stew',
  'fondue',
  'bowl_with_spoon',
  'green_salad',
  'popcorn',
  'butter',
  'salt',
  'canned_food',
  'bento',
  'rice_cracker',
  'rice_ball',
  'rice',
  'curry',
  'ramen',
  'spaghetti',
  'sweet_potato',
  'oden',
  'sushi',
  'fried_shrimp',
  'fish_cake',
  'moon_cake',
  'dango',
  'dumpling',
  'fortune_cookie',
  'takeout_box',
  'crab',
  'lobster',
  'shrimp',
  'squid',
  'oyster',
  'icecream',
  'shaved_ice',
  'ice_cream',
  'doughnut',
  'cookie',
  'birthday',
  'cake',
  'cupcake',
  'pie',
  'chocolate_bar',
  'candy',
  'lollipop',
  'custard',
  'honey_pot',
  'baby_bottle',
  'glass_of_milk',
  'coffee',
  'teapot',
  'tea',
  'sake',
  'champagne',
  'wine_glass',
  'cocktail',
  'tropical_drink',
  'beer',
  'beers',
  'clinking_glasses',
  'tumbler_glass',
  'pouring_liquid',
  'cup_with_straw',
  'bubble_tea',
  'beverage_box',
  'mate_drink',
  'ice_cube',
  'chopsticks',
  'knife_fork_plate',
  'fork_and_knife',
  'spoon',
  'hocho',
  'jar',
  'amphora',
  'jack_o_lantern',
  'christmas_tree',
  'fireworks',
  'sparkler',
  'firecracker',
  'balloon',
  'confetti_ball',
  'tanabata_tree',
  'bamboo',
  'dolls',
  'flags',
  'wind_chime',
  'rice_scene',
  'red_envelope',
  'ribbon',
  'gift',
  'reminder_ribbon',
  'admission_tickets',
  'ticket',
  'medal',
  'trophy',
  'sports_medal',
  'first_place_medal',
  'second_place_medal',
  'third_place_medal',
  'soccer',
  'baseball',
  'softball',
  'basketball',
  'volleyball',
  'football',
  'rugby_football',
  'tennis',
  'flying_disc',
  'bowling',
  'cricket_bat_and_ball',
  'field_hockey_stick_and_ball',
  'ice_hockey_stick_and_puck',
  'lacrosse',
  'table_tennis_paddle_and_ball',
  'badminton_racquet_and_shuttlecock',
  'boxing_glove',
  'martial_arts_uniform',
  'goal_net',
  'golf',
  'ice_skate',
  'fishing_pole_and_fish',
  'diving_mask',
  'running_shirt_with_sash',
  'ski',
  'sled',
  'curling_stone',
  'dart',
  'yo-yo',
  'kite',
  '8ball',
  'crystal_ball',
  'magic_wand',
  'nazar_amulet',
  'hamsa',
  'video_game',
  'joystick',
  'slot_machine',
  'game_die',
  'jigsaw',
  'teddy_bear',
  'pinata',
  'mirror_ball',
  'nesting_dolls',
  'spades',
  'hearts',
  'diamonds',
  'clubs',
  'chess_pawn',
  'black_joker',
  'mahjong',
  'flower_playing_cards',
  'performing_arts',
  'frame_with_picture',
  'art',
  'thread',
  'sewing_needle',
  'yarn',
  'knot',
  'earth_africa',
  'earth_americas',
  'earth_asia',
  'globe_with_meridians',
  'world_map',
  'japan',
  'compass',
  'snow_capped_mountain',
  'mountain',
  'volcano',
  'mount_fuji',
  'camping',
  'beach_with_umbrella',
  'desert',
  'desert_island',
  'national_park',
  'stadium',
  'classical_building',
  'building_construction',
  'bricks',
  'rock',
  'wood',
  'hut',
  'house_buildings',
  'derelict_house_building',
  'house',
  'house_with_garden',
  'office',
  'post_office',
  'european_post_office',
  'hospital',
  'bank',
  'hotel',
  'love_hotel',
  'convenience_store',
  'school',
  'department_store',
  'factory',
  'japanese_castle',
  'european_castle',
  'wedding',
  'tokyo_tower',
  'statue_of_liberty',
  'church',
  'mosque',
  'hindu_temple',
  'synagogue',
  'shinto_shrine',
  'kaaba',
  'fountain',
  'tent',
  'foggy',
  'night_with_stars',
  'cityscape',
  'sunrise_over_mountains',
  'sunrise',
  'city_sunset',
  'city_sunrise',
  'bridge_at_night',
  'hotsprings',
  'carousel_horse',
  'playground_slide',
  'ferris_wheel',
  'roller_coaster',
  'barber',
  'circus_tent',
  'steam_locomotive',
  'railway_car',
  'bullettrain_side',
  'bullettrain_front',
  'train2',
  'metro',
  'light_rail',
  'station',
  'tram',
  'monorail',
  'mountain_railway',
  'train',
  'bus',
  'oncoming_bus',
  'trolleybus',
  'minibus',
  'ambulance',
  'fire_engine',
  'police_car',
  'oncoming_police_car',
  'taxi',
  'oncoming_taxi',
  'car',
  'oncoming_automobile',
  'blue_car',
  'pickup_truck',
  'truck',
  'articulated_lorry',
  'tractor',
  'racing_car',
  'racing_motorcycle',
  'motor_scooter',
  'manual_wheelchair',
  'motorized_wheelchair',
  'auto_rickshaw',
  'bike',
  'scooter',
  'skateboard',
  'roller_skate',
  'busstop',
  'motorway',
  'railway_track',
  'oil_drum',
  'fuelpump',
  'wheel',
  'rotating_light',
  'traffic_light',
  'vertical_traffic_light',
  'octagonal_sign',
  'construction',
  'anchor',
  'ring_buoy',
  'boat',
  'canoe',
  'speedboat',
  'passenger_ship',
  'ferry',
  'motor_boat',
  'ship',
  'airplane',
  'small_airplane',
  'airplane_departure',
  'airplane_arriving',
  'parachute',
  'seat',
  'helicopter',
  'suspension_railway',
  'mountain_cableway',
  'aerial_tramway',
  'satellite',
  'rocket',
  'flying_saucer',
  'bellhop_bell',
  'luggage',
  'hourglass',
  'hourglass_flowing_sand',
  'watch',
  'alarm_clock',
  'stopwatch',
  'timer_clock',
  'mantelpiece_clock',
  'clock12',
  'clock1230',
  'clock1',
  'clock130',
  'clock2',
  'clock230',
  'clock3',
  'clock330',
  'clock4',
  'clock430',
  'clock5',
  'clock530',
  'clock6',
  'clock630',
  'clock7',
  'clock730',
  'clock8',
  'clock830',
  'clock9',
  'clock930',
  'clock10',
  'clock1030',
  'clock11',
  'clock1130',
  'new_moon',
  'waxing_crescent_moon',
  'first_quarter_moon',
  'moon',
  'full_moon',
  'waning_gibbous_moon',
  'last_quarter_moon',
  'waning_crescent_moon',
  'crescent_moon',
  'new_moon_with_face',
  'first_quarter_moon_with_face',
  'last_quarter_moon_with_face',
  'thermometer',
  'sunny',
  'full_moon_with_face',
  'sun_with_face',
  'ringed_planet',
  'star',
  'stars',
  'milky_way',
  'cloud',
  'partly_sunny',
  'thunder_cloud_and_rain',
  'mostly_sunny',
  'barely_sunny',
  'partly_sunny_rain',
  'rain_cloud',
  'snow_cloud',
  'lightning',
  'tornado',
  'fog',
  'wind_blowing_face',
  'cyclone',
  'rainbow',
  'closed_umbrella',
  'umbrella',
  'umbrella_with_rain_drops',
  'umbrella_on_ground',
  'zap',
  'snowflake',
  'snowman',
  'snowman_without_snow',
  'comet',
  'fire',
  'droplet',
  'ocean',
  'eyeglasses',
  'dark_sunglasses',
  'goggles',
  'lab_coat',
  'safety_vest',
  'necktie',
  'shirt',
  'jeans',
  'scarf',
  'gloves',
  'coat',
  'socks',
  'dress',
  'kimono',
  'sari',
  'one-piece_swimsuit',
  'briefs',
  'shorts',
  'bikini',
  'womans_clothes',
  'purse',
  'handbag',
  'pouch',
  'shopping_bags',
  'school_satchel',
  'thong_sandal',
  'mans_shoe',
  'athletic_shoe',
  'hiking_boot',
  'womans_flat_shoe',
  'high_heel',
  'sandal',
  'ballet_shoes',
  'boot',
  'crown',
  'womans_hat',
  'tophat',
  'mortar_board',
  'billed_cap',
  'military_helmet',
  'helmet_with_white_cross',
  'prayer_beads',
  'lipstick',
  'ring',
  'gem',
  'mute',
  'speaker',
  'sound',
  'loud_sound',
  'loudspeaker',
  'mega',
  'postal_horn',
  'bell',
  'no_bell',
  'musical_score',
  'musical_note',
  'notes',
  'studio_microphone',
  'level_slider',
  'control_knobs',
  'microphone',
  'headphones',
  'radio',
  'saxophone',
  'accordion',
  'guitar',
  'musical_keyboard',
  'trumpet',
  'violin',
  'banjo',
  'drum_with_drumsticks',
  'long_drum',
  'iphone',
  'calling',
  'phone',
  'telephone_receiver',
  'pager',
  'fax',
  'battery',
  'low_battery',
  'electric_plug',
  'computer',
  'desktop_computer',
  'printer',
  'keyboard',
  'three_button_mouse',
  'trackball',
  'minidisc',
  'floppy_disk',
  'cd',
  'dvd',
  'abacus',
  'movie_camera',
  'film_frames',
  'film_projector',
  'clapper',
  'tv',
  'camera',
  'camera_with_flash',
  'video_camera',
  'vhs',
  'mag',
  'mag_right',
  'candle',
  'bulb',
  'flashlight',
  'izakaya_lantern',
  'diya_lamp',
  'notebook_with_decorative_cover',
  'closed_book',
  'book',
  'green_book',
  'blue_book',
  'orange_book',
  'books',
  'notebook',
  'ledger',
  'page_with_curl',
  'scroll',
  'page_facing_up',
  'newspaper',
  'rolled_up_newspaper',
  'bookmark_tabs',
  'bookmark',
  'label',
  'moneybag',
  'coin',
  'yen',
  'dollar',
  'euro',
  'pound',
  'money_with_wings',
  'credit_card',
  'receipt',
  'chart',
  'email',
  'e-mail',
  'incoming_envelope',
  'envelope_with_arrow',
  'outbox_tray',
  'inbox_tray',
  'package',
  'mailbox',
  'mailbox_closed',
  'mailbox_with_mail',
  'mailbox_with_no_mail',
  'postbox',
  'ballot_box_with_ballot',
  'pencil2',
  'black_nib',
  'lower_left_fountain_pen',
  'lower_left_ballpoint_pen',
  'lower_left_paintbrush',
  'lower_left_crayon',
  'memo',
  'briefcase',
  'file_folder',
  'open_file_folder',
  'card_index_dividers',
  'date',
  'calendar',
  'spiral_note_pad',
  'spiral_calendar_pad',
  'card_index',
  'chart_with_upwards_trend',
  'chart_with_downwards_trend',
  'bar_chart',
  'clipboard',
  'pushpin',
  'round_pushpin',
  'paperclip',
  'linked_paperclips',
  'straight_ruler',
  'triangular_ruler',
  'scissors',
  'card_file_box',
  'file_cabinet',
  'wastebasket',
  'lock',
  'unlock',
  'lock_with_ink_pen',
  'closed_lock_with_key',
  'key',
  'old_key',
  'hammer',
  'axe',
  'pick',
  'hammer_and_pick',
  'hammer_and_wrench',
  'dagger_knife',
  'crossed_swords',
  'gun',
  'boomerang',
  'bow_and_arrow',
  'shield',
  'carpentry_saw',
  'wrench',
  'screwdriver',
  'nut_and_bolt',
  'gear',
  'compression',
  'scales',
  'probing_cane',
  'link',
  'chains',
  'hook',
  'toolbox',
  'magnet',
  'ladder',
  'alembic',
  'test_tube',
  'petri_dish',
  'dna',
  'microscope',
  'telescope',
  'satellite_antenna',
  'syringe',
  'drop_of_blood',
  'pill',
  'adhesive_bandage',
  'crutch',
  'stethoscope',
  'x-ray',
  'door',
  'elevator',
  'mirror',
  'window',
  'bed',
  'couch_and_lamp',
  'chair',
  'toilet',
  'plunger',
  'shower',
  'bathtub',
  'mouse_trap',
  'razor',
  'lotion_bottle',
  'safety_pin',
  'broom',
  'basket',
  'roll_of_paper',
  'bucket',
  'soap',
  'bubbles',
  'toothbrush',
  'sponge',
  'fire_extinguisher',
  'shopping_trolley',
  'smoking',
  'coffin',
  'headstone',
  'funeral_urn',
  'moyai',
  'placard',
  'identification_card',
  'atm',
  'put_litter_in_its_place',
  'potable_water',
  'wheelchair',
  'mens',
  'womens',
  'restroom',
  'baby_symbol',
  'wc',
  'passport_control',
  'customs',
  'baggage_claim',
  'left_luggage',
  'warning',
  'children_crossing',
  'no_entry_sign',
  'no_bicycles',
  'no_smoking',
  'do_not_litter',
  'non-potable_water',
  'no_pedestrians',
  'no_mobile_phones',
  'underage',
  'radioactive_sign',
  'biohazard_sign',
  'arrow_up',
  'arrow_upper_right',
  'arrow_right',
  'arrow_lower_right',
  'arrow_down',
  'arrow_lower_left',
  'arrow_left',
  'arrow_upper_left',
  'arrow_up_down',
  'left_right_arrow',
  'leftwards_arrow_with_hook',
  'arrow_right_hook',
  'arrow_heading_up',
  'arrow_heading_down',
  'arrows_clockwise',
  'arrows_counterclockwise',
  'back',
  'end',
  'on',
  'soon',
  'top',
  'place_of_worship',
  'atom_symbol',
  'om_symbol',
  'star_of_david',
  'wheel_of_dharma',
  'yin_yang',
  'latin_cross',
  'orthodox_cross',
  'star_and_crescent',
  'peace_symbol',
  'menorah_with_nine_branches',
  'six_pointed_star',
  'aries',
  'taurus',
  'gemini',
  'cancer',
  'leo',
  'virgo',
  'libra',
  'scorpius',
  'sagittarius',
  'capricorn',
  'aquarius',
  'pisces',
  'ophiuchus',
  'twisted_rightwards_arrows',
  'repeat',
  'repeat_one',
  'arrow_forward',
  'fast_forward',
  'black_right_pointing_double_triangle_with_vertical_bar',
  'black_right_pointing_triangle_with_double_vertical_bar',
  'arrow_backward',
  'rewind',
  'black_left_pointing_double_triangle_with_vertical_bar',
  'arrow_up_small',
  'arrow_double_up',
  'arrow_down_small',
  'arrow_double_down',
  'double_vertical_bar',
  'black_square_for_stop',
  'black_circle_for_record',
  'eject',
  'cinema',
  'low_brightness',
  'high_brightness',
  'signal_strength',
  'vibration_mode',
  'mobile_phone_off',
  'female_sign',
  'male_sign',
  'transgender_symbol',
  'heavy_multiplication_x',
  'heavy_plus_sign',
  'heavy_minus_sign',
  'heavy_division_sign',
  'heavy_equals_sign',
  'infinity',
  'bangbang',
  'interrobang',
  'question',
  'grey_question',
  'grey_exclamation',
  'exclamation',
  'wavy_dash',
  'currency_exchange',
  'heavy_dollar_sign',
  'medical_symbol',
  'recycle',
  'fleur_de_lis',
  'trident',
  'name_badge',
  'beginner',
  'o',
  'white_check_mark',
  'ballot_box_with_check',
  'negative_squared_cross_mark',
  'curly_loop',
  'loop',
  'part_alternation_mark',
  'eight_spoked_asterisk',
  'eight_pointed_black_star',
  'sparkle',
  'copyright',
  'registered',
  'tm',
  'hash',
  'keycap_star',
  'zero',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'keycap_ten',
  'capital_abcd',
  'abcd',
  '1234',
  'symbols',
  'abc',
  'a',
  'ab',
  'b',
  'cl',
  'cool',
  'free',
  'information_source',
  'id',
  'm',
  'new',
  'ng',
  'o2',
  'ok',
  'parking',
  'sos',
  'up',
  'vs',
  'koko',
  'sa',
  'u6708',
  'u6709',
  'u6307',
  'ideograph_advantage',
  'u5272',
  'u7121',
  'u7981',
  'accept',
  'u7533',
  'u5408',
  'u7a7a',
  'congratulations',
  'secret',
  'u55b6',
  'u6e80',
  'red_circle',
  'large_orange_circle',
  'large_yellow_circle',
  'large_green_circle',
  'large_blue_circle',
  'large_purple_circle',
  'large_brown_circle',
  'black_circle',
  'white_circle',
  'large_red_square',
  'large_orange_square',
  'large_yellow_square',
  'large_green_square',
  'large_blue_square',
  'large_purple_square',
  'large_brown_square',
  'black_large_square',
  'white_large_square',
  'black_medium_square',
  'white_medium_square',
  'black_medium_small_square',
  'white_medium_small_square',
  'black_small_square',
  'white_small_square',
  'large_orange_diamond',
  'large_blue_diamond',
  'small_orange_diamond',
  'small_blue_diamond',
  'small_red_triangle',
  'small_red_triangle_down',
  'diamond_shape_with_a_dot_inside',
  'radio_button',
  'white_square_button',
  'black_square_button',
  'checkered_flag',
  'cn',
  'crossed_flags',
  'de',
  'es',
  'flag-ac',
  'flag-ad',
  'flag-ae',
  'flag-af',
  'flag-ag',
  'flag-ai',
  'flag-al',
  'flag-am',
  'flag-ao',
  'flag-aq',
  'flag-ar',
  'flag-as',
  'flag-at',
  'flag-au',
  'flag-aw',
  'flag-ax',
  'flag-az',
  'flag-ba',
  'flag-bb',
  'flag-bd',
  'flag-be',
  'flag-bf',
  'flag-bg',
  'flag-bh',
  'flag-bi',
  'flag-bj',
  'flag-bl',
  'flag-bm',
  'flag-bn',
  'flag-bo',
  'flag-bq',
  'flag-br',
  'flag-bs',
  'flag-bt',
  'flag-bv',
  'flag-bw',
  'flag-by',
  'flag-bz',
  'flag-ca',
  'flag-cc',
  'flag-cd',
  'flag-cf',
  'flag-cg',
  'flag-ch',
  'flag-ci',
  'flag-ck',
  'flag-cl',
  'flag-cm',
  'flag-co',
  'flag-cp',
  'flag-cr',
  'flag-cu',
  'flag-cv',
  'flag-cw',
  'flag-cx',
  'flag-cy',
  'flag-cz',
  'flag-dg',
  'flag-dj',
  'flag-dk',
  'flag-dm',
  'flag-do',
  'flag-dz',
  'flag-ea',
  'flag-ec',
  'flag-ee',
  'flag-eg',
  'flag-eh',
  'flag-england',
  'flag-er',
  'flag-et',
  'flag-eu',
  'flag-fi',
  'flag-fj',
  'flag-fk',
  'flag-fm',
  'flag-fo',
  'flag-ga',
  'flag-gd',
  'flag-ge',
  'flag-gf',
  'flag-gg',
  'flag-gh',
  'flag-gi',
  'flag-gl',
  'flag-gm',
  'flag-gn',
  'flag-gp',
  'flag-gq',
  'flag-gr',
  'flag-gs',
  'flag-gt',
  'flag-gu',
  'flag-gw',
  'flag-gy',
  'flag-hk',
  'flag-hm',
  'flag-hn',
  'flag-hr',
  'flag-ht',
  'flag-hu',
  'flag-ic',
  'flag-id',
  'flag-ie',
  'flag-il',
  'flag-im',
  'flag-in',
  'flag-io',
  'flag-iq',
  'flag-ir',
  'flag-is',
  'flag-je',
  'flag-jm',
  'flag-jo',
  'flag-ke',
  'flag-kg',
  'flag-kh',
  'flag-ki',
  'flag-km',
  'flag-kn',
  'flag-kp',
  'flag-kw',
  'flag-ky',
  'flag-kz',
  'flag-la',
  'flag-lb',
  'flag-lc',
  'flag-li',
  'flag-lk',
  'flag-lr',
  'flag-ls',
  'flag-lt',
  'flag-lu',
  'flag-lv',
  'flag-ly',
  'flag-ma',
  'flag-mc',
  'flag-md',
  'flag-me',
  'flag-mf',
  'flag-mg',
  'flag-mh',
  'flag-mk',
  'flag-ml',
  'flag-mm',
  'flag-mn',
  'flag-mo',
  'flag-mp',
  'flag-mq',
  'flag-mr',
  'flag-ms',
  'flag-mt',
  'flag-mu',
  'flag-mv',
  'flag-mw',
  'flag-mx',
  'flag-my',
  'flag-mz',
  'flag-na',
  'flag-nc',
  'flag-ne',
  'flag-nf',
  'flag-ng',
  'flag-ni',
  'flag-nl',
  'flag-no',
  'flag-np',
  'flag-nr',
  'flag-nu',
  'flag-nz',
  'flag-om',
  'flag-pa',
  'flag-pe',
  'flag-pf',
  'flag-pg',
  'flag-ph',
  'flag-pk',
  'flag-pl',
  'flag-pm',
  'flag-pn',
  'flag-pr',
  'flag-ps',
  'flag-pt',
  'flag-pw',
  'flag-py',
  'flag-qa',
  'flag-re',
  'flag-ro',
  'flag-rs',
  'flag-rw',
  'flag-sa',
  'flag-sb',
  'flag-sc',
  'flag-scotland',
  'flag-sd',
  'flag-se',
  'flag-sg',
  'flag-sh',
  'flag-si',
  'flag-sj',
  'flag-sk',
  'flag-sl',
  'flag-sm',
  'flag-sn',
  'flag-so',
  'flag-sr',
  'flag-ss',
  'flag-st',
  'flag-sv',
  'flag-sx',
  'flag-sy',
  'flag-sz',
  'flag-ta',
  'flag-tc',
  'flag-td',
  'flag-tf',
  'flag-tg',
  'flag-th',
  'flag-tj',
  'flag-tk',
  'flag-tl',
  'flag-tm',
  'flag-tn',
  'flag-to',
  'flag-tr',
  'flag-tt',
  'flag-tv',
  'flag-tw',
  'flag-tz',
  'flag-ua',
  'flag-ug',
  'flag-um',
  'flag-un',
  'flag-uy',
  'flag-uz',
  'flag-va',
  'flag-vc',
  'flag-ve',
  'flag-vg',
  'flag-vi',
  'flag-vn',
  'flag-vu',
  'flag-wales',
  'flag-wf',
  'flag-ws',
  'flag-xk',
  'flag-ye',
  'flag-yt',
  'flag-za',
  'flag-zm',
  'flag-zw',
  'fr',
  'gb',
  'it',
  'jp',
  'kr',
  'pirate_flag',
  'ru',
  'transgender_flag',
  'triangular_flag_on_post',
  'us',
  'waving_black_flag',
  'waving_white_flag',
];

export const config: Configuration = {
  accountSid,
  flexFlowSid,
  defaultLanguage,
  translations,
  preEngagementConfig,
  closedHours,
  holidayHours,
  checkOpenHours,
  mapHelplineLanguage,
  memberDisplayOptions,
  captureIp,
  contactType,
  blockedEmojis,
  enableRecaptcha,
  twilioServicesUrl: new URL(`https://hrm-staging.tl.techmatters.org/lambda/twilio/account-scoped/${accountSid}`),
};
