export const keyboardGuide = [
  { description: 'Toggle keyboard guide', keys: 'G' },
  { description: 'Toggle sidebar', keys: 'S' },
  { description: 'Toggle availability', keys: 'O' },
  { description: 'Alert Custom Shortcut', keys: 'C' },
  // { description: 'Select next task', keys: '`' },
  // { description: 'Select previous task', keys: 'Shift + `' },
  // { description: 'Accept selected task', keys: 'A' },
  // { description: 'Mute call', keys: 'M' },
  // { description: 'Hold call', keys: 'H' },
  // { description: 'Unhold call', keys: 'U' },
  // { description: 'Hangup call', keys: 'H' },
  // { description: 'Wrapup task', keys: 'W' },
  // { description: 'Complete task', keys: 'C' },
];
