# This is a basic workflow to publish a Twilio Flex-plugins with Github Actions

name: End to End Testing Development release

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      changelog:
        description: Release Changelog - Add a comment about the changes to be included in this release.
        required: true
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      E2E_DEV_ACCOUNT_SID:
        required: true
      E2E_DEV_AUTH_TOKEN:
        required: true
    inputs:
      changelog:
        description: Release Changelog - Add a comment about the changes to be included in this release.
        required: true
        type: string
      send-slack-message:
        description: 'Specifies if should send a Slack message at the end of successful run. Defaults to true'
        required: false
        default: 'true'
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # Call main-action to compile and deploy
      - name: Executing main-action
        uses: ./.github/actions/main-action
        with:
          account-sid: ${{ secrets.E2E_DEV_ACCOUNT_SID }}
          auth-token: ${{ secrets.E2E_DEV_AUTH_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          send-slack-message: ${{ inputs.send-slack-message }}
