# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

name: Run full QA on push

on:
  push:
    branches: [master]

jobs:
  deploy-flex:
    uses: ./.github/workflows/flex-deploy.yml
    secrets: inherit
    with:
      helpline_code: E2E
      environment_code: DEV
      changelog: "Automated release"
      send-slack-message: 'false'

  deploy-webchat:
    uses: ./.github/workflows/webchat-deploy.yml
    secrets: inherit
    with:
      helpline_code: E2E
      environment: development
      send-slack-message: 'false'

  run-e2e-tests:
    needs: [deploy-flex, deploy-webchat]

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Flex Plugin
        uses: ./.github/actions/install-flex-plugin

      - name: Run e2e tests
        uses: ./.github/actions/run-e2e-tests
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Send Slack notifying failure
      - name: Send Slack notification on failure
        uses: ./.github/actions/notify-deploys
        if: failure()
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
          slack-message: "`[Flex]` QA run for ${{ github.ref_type }} `${{ github.ref_name }}` failed. Please check the logs for more details."
          channel-id: "#aselo-engineering"
        env:
          SLACK_BOT_TOKEN: ${{ env.GITHUB_ACTIONS_SLACK_BOT_TOKEN }}

      - name: Create Version Tag
        id: create-version-tag
        uses: ./.github/actions/create-tag-based-on-regex
        with:
          search_text: ${{ github.event.pull_request.title }}
          regex: 'v[0-9]+\.[0-9]+\.[0-9]+'

      - name: Create Ticket Tag
        if: ${{ steps.create-version-tag.outputs.tag_created == 'false' }}
        uses: ./.github/actions/create-tag-based-on-regex
        with:
          search_text: ${{ github.event.pull_request.title }}
          regex: 'CHI-[0-9]+'
