# This is a basic workflow to run terraform plan for a twilio IAC account with Github Actions

name: Terraform Plan

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      helpline:
        description: Directory name of helpline to run plan against
        required: true
        type: string
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    name: clean dynamic envs
    runs-on: ubuntu-latest

    container:
      image: public.ecr.aws/techmatters/terraform:1.3.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Plan
        run: |
          cd twilio-iac/${{ inputs.helpline }}
          terraform init
          terraform plan
