# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

name: Deploy Webchat to all Staging Helplines

on:
  workflow_dispatch:

jobs:
  configure:
    name: Determine Configuration
    runs-on: ubuntu-latest
    outputs:
      target_helplines: ${{ steps.determine-target-helplines.outputs.target_helplines }}
    steps:
      - uses: actions/checkout@v4
      - id: determine-target-helplines
        shell: bash
        run: |
          helplines=$(node webchat/scripts/output-helplines-for-environment.js staging)
          echo "target_helplines=$helplines" >> $GITHUB_OUTPUT
  deploy-helplines:
    name: Deploy to multiple helplines
    needs: configure
    uses: ./.github/workflows/deploy-multiple-helplines.yml
    secrets: inherit
    with:
      project: webchat
      helplines: ${{ needs.configure.outputs.target_helplines }}
      environments: '[ "staging" ]'