# This is a basic workflow to publish a Twilio Flex-plugins with Github Actions

name: Zambia Production release

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      changelog:
        description: Release Changelog - Add a comment about the changes to be included in this release.
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # Call main-action to compile and deploy
      - name: Executing main-action
        uses: ./.github/actions/main-action
        with:
          account-sid: ${{ secrets.ZM_PROD_ACCOUNT_SID }}
          auth-token: ${{ secrets.ZM_PROD_AUTH_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
